// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gazgeminiofjtbunnclv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhemdlbWluaW9manRidW5uY2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzAyNjcsImV4cCI6MjA2NzgwNjI2N30.FEChpCsU4wASSVgePFKE7a5ZYT3NZM0ya7MMjc3l9UY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});